const getters = {
  sidebar: state => state.app.sidebar,
  sidebarMode: state => state.app.sidebarMode,
  // leftSidebarRouters: state => state.app.leftSidebarRouters,
  leftSidebarRouters: state => state.permission.leftSidebarRouters,
  tabsSidebarRouters: state => state.permission.tabsSidebarRouters,
  tabsActiveName: state => state.permission.tabsActiveName,
  childRouters: state => state.app.childRouters,
  size: state => state.app.size,
  device: state => state.app.device,
  showSideTool: state => state.app.showSideTool,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  dict: state => state.dict.dict,
  creditDict: state => state.dict.creditDict,
  contractDict: state => state.dict.contractDict,
  province: state => state.dict.province,
  area: state => state.dict.area
}
export default getters
